/* ============================================================
   data.js — ALL site content lives here.
   To add/edit projects, skills or experience, only touch this
   file. No HTML changes required.
   ============================================================ */

const SITE_DATA = {

  /* ---------- Typed tagline phrases (hero) ---------- */
  taglines: [
    'AI & Machine Learning',
    'Computer Vision Research',
    '3D Gaussian Splatting',
    'Explainable AI',
    'Deep Learning',
  ],

  /* ---------- About bio (HTML allowed) ---------- */
  bio: `
    <p>I'm an <strong>M.Tech Artificial Intelligence</strong> student at the
    <strong>Indian Institute of Science (IISc), Bengaluru</strong>, with a
    B.Tech in Computer Science from <strong>IIT Dharwad</strong> (CGPA 9.61).</p>
    <p>My work sits at the intersection of <strong>computer vision</strong> and
    <strong>interpretable deep learning</strong> — from refining Class Activation
    Maps with SVD, to pruning 3D Gaussian scene representations for real-time
    novel-view synthesis, to detecting clinical depression from speech
    spectrograms.</p>
    <p>I enjoy taking research ideas all the way to working systems: training the
    models, building the APIs, and shipping the product around them.</p>
  `,

  /* ---------- Skills, grouped by area ---------- */
  skills: [
    {
      group: 'Research Areas',
      items: ['Computer Vision', '3D Scene Representation', 'Explainable AI', 'Deep Learning', 'NLP', 'Speech Processing'],
    },
    {
      group: 'Programming',
      items: ['Python', 'C / C++', 'Java', 'JavaScript', 'SQL'],
    },
    {
      group: 'Frameworks & Tools',
      items: ['PyTorch', 'TensorFlow', 'scikit-learn', 'OpenCV', 'React', 'Node.js', 'MongoDB', 'Git', 'Linux'],
    },
  ],

  /* ----------------------------------------------------------
     Publications.
       authors: list of names; 'Srihari K G' is auto-underlined.
       links:   project / paper / code URLs — omit any to show it
                as "coming soon".
       image:   optional teaser/thumbnail path.
     ---------------------------------------------------------- */
  publications: [
    {
      title: 'AdaptiveSplat: Texture Aware Controllable 3D Gaussian Allocation for Feed-Forward Reconstruction',
      authors: ['Badrinath Singhal', 'Srihari K G', 'Sreehari Iyer', 'Ankit Dhiman', 'Venkatesh Babu Radhakrishnan'],
      venue: 'ECCV 2026',
      venueNote: 'Accepted',
      year: '2026',
      image: 'assets/img/pub-adaptivesplat.jpeg',
      links: {}, // project / paper / code — coming soon
    },
  ],

  /* ----------------------------------------------------------
     Gallery: NOT configured here. Just create a folder under
     assets/gallery/ — the folder name becomes the event title.
     Optional caption.txt inside the folder adds a caption.
     (js/gallery.js is auto-generated by scripts/build_gallery.py,
     which runs automatically on deploy.)
     ---------------------------------------------------------- */

  /* ---------- Project categories (order = filter button order) ---------- */
  categories: ['All', 'Research', 'Computer Vision', 'NLP', 'Machine Learning', 'Web Dev'],

  /* ----------------------------------------------------------
     Projects.
     images: list of paths (first one = card thumbnail).
       Swap the placeholder SVGs in assets/img/ for real
       screenshots — keep filenames or update the paths here.
     tags: must match entries in `categories` (except 'All').
     links: live / github are optional — omit freely.
     ---------------------------------------------------------- */
  projects: [
    {
      title: '3D Gaussian Splatting — Texture-Aware Pruning',
      description: 'Feed-forward, controllable 3D Gaussian scene representations without per-scene optimization. Texture-aware pruning via spatial–color clustering and wavelet-based complexity ranking removes redundant Gaussians while preserving rendering quality — enabling real-time novel-view synthesis.',
      tags: ['Research', 'Computer Vision'],
      stack: ['PyTorch', '3D Gaussian Splatting', 'CUDA', 'Wavelets'],
      images: ['assets/img/p-gaussian.svg', 'assets/img/p-gaussian-2.svg'],
      links: { github: 'https://github.com/sriharikg2003/DenseNopo' },
      featured: true,
    },
    {
      title: '3D Editing via Latent Steering',
      description: 'Exploring controllable 3D scene editing by steering latent representations — manipulating learned features to apply semantic edits to 3D content.',
      tags: ['Research', 'Computer Vision'],
      stack: ['PyTorch', 'Diffusion Models', '3D Vision'],
      images: ['assets/img/p-latent.svg'],
      links: { github: 'https://github.com/sriharikg2003/3D_Editing_Latent_Steering' },
      featured: true,
    },
    {
      title: 'SVD-CAM — Explainable AI',
      description: 'A refinement method for Class Activation Maps using Singular Value Decomposition that improves visual interpretability. Benchmarked against CAM, GradCAM and Integrated GradCAM, including layered variations.',
      tags: ['Research', 'Computer Vision'],
      stack: ['PyTorch', 'XAI', 'SVD', 'GradCAM'],
      images: ['assets/img/p-svdcam.svg'],
      links: { github: 'https://github.com/sriharikg2003/svdcam' },
      featured: true,
    },
    {
      title: 'Clinical Depression Detection',
      description: 'Detecting clinical depression from modulation spectrograms of speech using deep learning, under Prof. S. R. Mahadeva Prasanna at IIT Dharwad. Compared ViT, MLP-Mixer and ConvMixer; best results with ConvMixer + SMOTE on the EATD corpus.',
      tags: ['Research', 'Machine Learning'],
      stack: ['PyTorch', 'ConvMixer', 'ViT', 'Speech Processing', 'SMOTE'],
      images: ['assets/img/p-depression.svg'],
      links: { github: 'https://github.com/sriharikg2003/Depression-Detection' },
      featured: true,
    },
    {
      title: 'Sanskrit Text Classification (NLP)',
      description: 'Classifying under-resourced Sanskrit verses with high accuracy under Prof. Kushal Shah. Explored statistical features, probabilistic ML models and deep neural networks to uncover linguistic patterns in ancient texts.',
      tags: ['Research', 'NLP'],
      stack: ['Python', 'scikit-learn', 'Deep Learning', 'Statistics'],
      images: ['assets/img/p-sanskrit.svg'],
      links: { github: 'https://github.com/sriharikg2003/NLP-Sanskrit' },
    },
    {
      title: 'Clap-Pattern & Musical-Syllable Detection',
      description: 'AI features for Shaale, a self-learning Indian classical music platform. Audio-to-spectrogram vision models for real-time musical-syllable prediction and clap-pattern detection, deployed behind REST APIs.',
      tags: ['Machine Learning', 'Computer Vision'],
      stack: ['Python', 'TensorFlow', 'Spectrograms', 'REST APIs'],
      images: ['assets/img/p-clap.svg'],
      links: { github: 'https://github.com/sriharikg2003/Clap-detector' },
    },
    {
      title: 'Vision Vault — Photo Gallery App',
      description: 'Full-stack photo gallery with uploads stored in MongoDB GridFS. Browse, organize and serve images through an Express API with a React front end.',
      tags: ['Web Dev'],
      stack: ['React', 'Node.js', 'Express', 'MongoDB', 'GridFS'],
      images: ['assets/img/p-visionvault.svg'],
      links: { github: 'https://github.com/sriharikg2003/Vision-Vault-App' },
    },
    {
      title: 'AlumSphere',
      description: 'A platform connecting students and alumni — profiles, networking and opportunity sharing built on the MERN stack.',
      tags: ['Web Dev'],
      stack: ['React', 'Node.js', 'Express', 'MongoDB'],
      images: ['assets/img/p-alumsphere.svg'],
      links: { github: 'https://github.com/sriharikg2003/AlumSphere' },
    },
    {
      title: 'Blog Website',
      description: 'Compose posts and read others\' blogs — a clean multi-user blogging app with authentication and a writing-first UI.',
      tags: ['Web Dev'],
      stack: ['Node.js', 'Express', 'MongoDB', 'EJS'],
      images: ['assets/img/p-blog.svg'],
      links: { github: 'https://github.com/sriharikg2003/Blog-Website' },
    },
    {
      title: 'Moisture Minds — ML Contest (Parsec 3.0)',
      description: 'Competition entry predicting soil moisture from sensor data — feature engineering and model ensembling under contest constraints.',
      tags: ['Machine Learning'],
      stack: ['Python', 'scikit-learn', 'XGBoost', 'Pandas'],
      images: ['assets/img/p-moisture.svg'],
      links: { github: 'https://github.com/sriharikg2003/Moisture-Minds' },
    },
  ],

  /* ---------- Experience / education timeline (top = most recent) ---------- */
  timeline: [
    {
      period: '2025 — 2027',
      title: 'M.Tech, Artificial Intelligence',
      org: 'Indian Institute of Science, Bengaluru',
      points: ['CGPA 8.7 · Research focus on computer vision and 3D scene representation.'],
      type: 'education',
    },
    {
      period: 'Jan 2025 — Jul 2025',
      title: 'Project Assistant',
      org: 'Indian Institute of Science, Bengaluru',
      points: [
        'Developed feed-forward methods for controllable, efficient 3D Gaussian scene representations — no per-scene optimization or post-pruning fine-tuning.',
        'Designed texture-aware pruning using spatial–color clustering and wavelet-based complexity ranking.',
        'Achieved real-time novel-view synthesis with significantly fewer Gaussians on real-world and synthetic datasets.',
      ],
      type: 'work',
    },
    {
      period: 'Feb 2024 — Jun 2024',
      title: 'ML Intern',
      org: 'Shaale',
      points: [
        'Built AI features for a self-learning music platform enabling real-time interaction.',
        'Developed audio-to-spectrogram vision models for musical-syllable prediction and clap-pattern detection.',
        'Deployed models via REST APIs integrated with the platform backend.',
      ],
      type: 'work',
    },
    {
      period: 'May 2023 — Jul 2023',
      title: 'NLP Research Intern',
      org: 'with Prof. Kushal Shah',
      points: [
        'Classified under-resourced Sanskrit texts with high accuracy using statistical features and ML models.',
        'Investigated deep neural networks to uncover deeper linguistic patterns.',
      ],
      type: 'work',
    },
    {
      period: '2021 — 2025',
      title: 'B.Tech, Computer Science & Engineering',
      org: 'Indian Institute of Technology Dharwad',
      points: ['CGPA 9.61 · Coursework spanning AI, OS, DSA, computer architecture and scientific computing.'],
      type: 'education',
    },
  ],
};
