/* AUTO-GENERATED by scripts/build_gallery.py — do not edit.
   Add event folders under assets/gallery/ instead. */
const GALLERY_DATA = [
  {
    "event": "B.Tech Convocation",
    "caption": "",
    "photos": [
      "assets/gallery/01 B.Tech Convocation/CS_batch.jpeg",
      "assets/gallery/01 B.Tech Convocation/Friends_0.jpeg",
      "assets/gallery/01 B.Tech Convocation/Friends_2.jpeg",
      "assets/gallery/01 B.Tech Convocation/Friends_3.jpeg",
      "assets/gallery/01 B.Tech Convocation/Full_batch.jpeg",
      "assets/gallery/01 B.Tech Convocation/Gang_1.jpeg",
      "assets/gallery/01 B.Tech Convocation/throw.jpeg"
    ]
  }
];
