/* AUTO-GENERATED by scripts/build_gallery.py — do not edit.
   Add event folders under assets/gallery/ instead. */
const GALLERY_DATA = [
  {
    "event": "IIT Convocation",
    "caption": "",
    "photos": [
      "assets/gallery/01 IIT Convocation/CS_batch.jpeg",
      "assets/gallery/01 IIT Convocation/Director.jpeg",
      "assets/gallery/01 IIT Convocation/Friend_0.jpeg",
      "assets/gallery/01 IIT Convocation/Friends_1.jpeg",
      "assets/gallery/01 IIT Convocation/Friends_2.jpeg",
      "assets/gallery/01 IIT Convocation/Full_batch.jpeg",
      "assets/gallery/01 IIT Convocation/gang_1.jpeg",
      "assets/gallery/01 IIT Convocation/throw.jpeg"
    ]
  }
];
