#!/usr/bin/env python3
"""
Generates js/gallery.js from the folder structure under assets/gallery/.

Usage: just create folders — no code required.

    assets/gallery/
    ├── 01 Research Symposium - IISc/     ← folder name = event title
    │   ├── photo1.jpg                    ← photos, shown alphabetically
    │   ├── photo2.jpg
    │   └── caption.txt                   ← optional one-line caption
    └── 02 Another Event/
        └── ...

Rules:
- A leading number prefix ("01 ", "2-", "03_") is used only for ordering
  and is stripped from the displayed title.
- Events appear in alphabetical folder order (use number prefixes to order).
- caption.txt is optional; its contents appear under the event title.
- Folders with no images are skipped.

This script runs automatically in the GitHub Actions deploy workflow,
so committing a new folder is all that's needed. To refresh a local
preview, run:  python3 scripts/build_gallery.py
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GALLERY_DIR = ROOT / "assets" / "gallery"
OUT_FILE = ROOT / "js" / "gallery.js"
IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".webp", ".gif", ".svg", ".avif"}

events = []
if GALLERY_DIR.is_dir():
    for folder in sorted(GALLERY_DIR.iterdir(), key=lambda p: p.name.lower()):
        if not folder.is_dir() or folder.name.startswith("."):
            continue

        photos = sorted(
            p for p in folder.iterdir()
            if p.suffix.lower() in IMAGE_EXTS and not p.name.startswith(".")
        )
        if not photos:
            continue

        # "01 Event Name" / "2-Event" / "03_Event" → "Event Name"
        title = re.sub(r"^\d+[\s._-]+", "", folder.name).strip() or folder.name

        caption_file = folder / "caption.txt"
        caption = caption_file.read_text(encoding="utf-8").strip() if caption_file.exists() else ""

        events.append({
            "event": title,
            "caption": caption,
            "photos": [str(p.relative_to(ROOT)) for p in photos],
        })

OUT_FILE.write_text(
    "/* AUTO-GENERATED by scripts/build_gallery.py — do not edit.\n"
    "   Add event folders under assets/gallery/ instead. */\n"
    f"const GALLERY_DATA = {json.dumps(events, indent=2, ensure_ascii=False)};\n",
    encoding="utf-8",
)
print(f"gallery.js written: {len(events)} event(s), "
      f"{sum(len(e['photos']) for e in events)} photo(s)")
